// <auto-generated />
using FrequentQuestions.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FrequentQuestions.Migrations
{
    [DbContext(typeof(QuestionContext))]
    [Migration("20201004160400_Topic")]
    partial class Topic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FrequentQuestions.Models.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = "GN",
                            CategoryName = "General"
                        },
                        new
                        {
                            CategoryID = "HS",
                            CategoryName = "History"
                        });
                });

            modelBuilder.Entity("FrequentQuestions.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Faq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("QuestionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Answer = "A CSS framework for creating responsive web apps for multiple screen sizes",
                            CategoryId = "GN",
                            Faq = "What is Bootstrap?",
                            TopicId = "BS"
                        },
                        new
                        {
                            QuestionId = 2,
                            Answer = "A general purpose object oriented language that uses a concise, Java-like syntax.",
                            CategoryId = "GN",
                            Faq = "What is C#?",
                            TopicId = "C#"
                        },
                        new
                        {
                            QuestionId = 3,
                            Answer = "A general purpose scripting language that executes in a web browser.",
                            CategoryId = "GN",
                            Faq = "What is JavaScript?",
                            TopicId = "JS"
                        },
                        new
                        {
                            QuestionId = 4,
                            Answer = "In 2011",
                            CategoryId = "HS",
                            Faq = "When was Bootstrap first released?",
                            TopicId = "BS"
                        },
                        new
                        {
                            QuestionId = 5,
                            Answer = "In 2002",
                            CategoryId = "HS",
                            Faq = "When was C# first released?",
                            TopicId = "C#"
                        });
                });

            modelBuilder.Entity("FrequentQuestions.Models.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TopicName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = "BS",
                            TopicName = "Bootstrap"
                        },
                        new
                        {
                            TopicId = "C#",
                            TopicName = "C#"
                        },
                        new
                        {
                            TopicId = "JS",
                            TopicName = "JavaScript"
                        });
                });

            modelBuilder.Entity("FrequentQuestions.Models.Question", b =>
                {
                    b.HasOne("FrequentQuestions.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("FrequentQuestions.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId");
                });
#pragma warning restore 612, 618
        }
    }
}
