// <auto-generated />
using FrequentQuestions.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FrequentQuestions.Migrations
{
    [DbContext(typeof(QuestionContext))]
    [Migration("20201004152145_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FrequentQuestions.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faq")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Answer = "A CSS framework for creating responsive web apps for multiple screen sizes",
                            Faq = "What is Bootstrap?"
                        },
                        new
                        {
                            QuestionId = 2,
                            Answer = "A general purpose object oriented language that uses a concise, Java-like syntax.",
                            Faq = "What is C#?"
                        },
                        new
                        {
                            QuestionId = 3,
                            Answer = "A general purpose scripting language that executes in a web browser.",
                            Faq = "What is JavaScript?"
                        },
                        new
                        {
                            QuestionId = 4,
                            Answer = "In 2011",
                            Faq = "When was Bootstrap first released?"
                        },
                        new
                        {
                            QuestionId = 5,
                            Answer = "In 2002",
                            Faq = "When was C# first released?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
