// <auto-generated />
using Faqs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Faqs.Migrations
{
    [DbContext(typeof(FaqsContext))]
    [Migration("20201014231428_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Faqs.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "gen",
                            Name = "General"
                        },
                        new
                        {
                            CategoryId = "hist",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("Faqs.Models.FAQ", b =>
                {
                    b.Property<int>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FaqId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            FaqId = 1,
                            Answer = "A CSS framework for creating responsive web apps for multiple screen sizes",
                            CategoryId = "gen",
                            Question = "What is Bootstrap",
                            TopicId = "boot"
                        },
                        new
                        {
                            FaqId = 2,
                            Answer = "A general purpose object oriented language that uses a consise, Java-like syntax.",
                            CategoryId = "gen",
                            Question = "What is C#",
                            TopicId = "cs"
                        },
                        new
                        {
                            FaqId = 3,
                            Answer = "A general purpose scripting language that executes in a web browser",
                            CategoryId = "gen",
                            Question = "What is JavaScript",
                            TopicId = "js"
                        },
                        new
                        {
                            FaqId = 4,
                            Answer = "In 2011",
                            CategoryId = "hist",
                            Question = "When was Bootstrap first released?",
                            TopicId = "boot"
                        },
                        new
                        {
                            FaqId = 5,
                            Answer = "In 2002",
                            CategoryId = "hist",
                            Question = "When was C# first released?",
                            TopicId = "cs"
                        });
                });

            modelBuilder.Entity("Faqs.Models.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = "cs",
                            Name = "C#"
                        },
                        new
                        {
                            TopicId = "js",
                            Name = "JavaScript"
                        },
                        new
                        {
                            TopicId = "boot",
                            Name = "Bootstrap"
                        });
                });

            modelBuilder.Entity("Faqs.Models.FAQ", b =>
                {
                    b.HasOne("Faqs.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Faqs.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId");
                });
#pragma warning restore 612, 618
        }
    }
}
